-- Initialize CPTM user and schema for Oracle Docker
-- This script runs when Oracle XE starts in Docker

ALTER SESSION SET CONTAINER=XEPDB1;

-- Create user CPTM if not exists
BEGIN
  BEGIN
    DROP USER CPTM CASCADE;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/

CREATE USER CPTM IDENTIFIED BY root;

-- Grant permissions
GRANT CONNECT, RESOURCE, DBA TO CPTM;
GRANT CREATE SESSION TO CPTM;
GRANT CREATE TABLE TO CPTM;
GRANT CREATE SEQUENCE TO CPTM;
GRANT CREATE PROCEDURE TO CPTM;
GRANT UNLIMITED TABLESPACE TO CPTM;

-- Commit changes
COMMIT;

ALTER SESSION SET CURRENT_SCHEMA=CPTM;
