-- SQL Seed Data para CPTM - Oracle Database
-- Usar APENAS se executar migrations manualmente
-- Recomendado: usar HasData() do EF Core via migrations

-- TB_PERFIL_USUARIO
INSERT INTO TB_PERFIL_USUARIO (ID_PERFIL, DS_PERFIL) VALUES (1, 'ADMINISTRADOR');
INSERT INTO TB_PERFIL_USUARIO (ID_PERFIL, DS_PERFIL) VALUES (2, 'USUARIO_CAMPO');

-- TB_STATUS_REGISTRO
INSERT INTO TB_STATUS_REGISTRO (ID_STATUS, DS_STATUS) VALUES (1, 'ATIVO');
INSERT INTO TB_STATUS_REGISTRO (ID_STATUS, DS_STATUS) VALUES (2, 'INATIVO');
INSERT INTO TB_STATUS_REGISTRO (ID_STATUS, DS_STATUS) VALUES (3, 'PENDENTE');
INSERT INTO TB_STATUS_REGISTRO (ID_STATUS, DS_STATUS) VALUES (4, 'SINCRONIZADO');

-- TB_STATUS_DESVIO_AMBIENTAL
INSERT INTO TB_STATUS_DESVIO_AMBIENTAL (ID_STATUS, DS_STATUS) VALUES (1, 'ABERTO');
INSERT INTO TB_STATUS_DESVIO_AMBIENTAL (ID_STATUS, DS_STATUS) VALUES (2, 'EM_ANALISE');
INSERT INTO TB_STATUS_DESVIO_AMBIENTAL (ID_STATUS, DS_STATUS) VALUES (3, 'RESOLVIDO');
INSERT INTO TB_STATUS_DESVIO_AMBIENTAL (ID_STATUS, DS_STATUS) VALUES (4, 'CANCELADO');

-- TB_TIPO_EFLUENTE
INSERT INTO TB_TIPO_EFLUENTE (ID_TIPO_EFLUENTE, DS_TIPO_EFLUENTE) VALUES (1, 'ESGOTO');
INSERT INTO TB_TIPO_EFLUENTE (ID_TIPO_EFLUENTE, DS_TIPO_EFLUENTE) VALUES (2, 'OLEO');
INSERT INTO TB_TIPO_EFLUENTE (ID_TIPO_EFLUENTE, DS_TIPO_EFLUENTE) VALUES (3, 'QUIMICO');
INSERT INTO TB_TIPO_EFLUENTE (ID_TIPO_EFLUENTE, DS_TIPO_EFLUENTE) VALUES (4, 'INDUSTRIAL');
INSERT INTO TB_TIPO_EFLUENTE (ID_TIPO_EFLUENTE, DS_TIPO_EFLUENTE) VALUES (5, 'AGUA_CONTAMINADA');

-- TB_VIA_CPTM
INSERT INTO TB_VIA_CPTM (ID_VIA, DS_VIA) VALUES (1, 'VIA_1');
INSERT INTO TB_VIA_CPTM (ID_VIA, DS_VIA) VALUES (2, 'VIA_2');

-- TB_LINHA_CPTM
INSERT INTO TB_LINHA_CPTM (ID_LINHA, DS_LINHA) VALUES (1, 'LINHA_7');
INSERT INTO TB_LINHA_CPTM (ID_LINHA, DS_LINHA) VALUES (2, 'LINHA_8');
INSERT INTO TB_LINHA_CPTM (ID_LINHA, DS_LINHA) VALUES (3, 'LINHA_9');
INSERT INTO TB_LINHA_CPTM (ID_LINHA, DS_LINHA) VALUES (4, 'LINHA_10');
INSERT INTO TB_LINHA_CPTM (ID_LINHA, DS_LINHA) VALUES (5, 'LINHA_11');
INSERT INTO TB_LINHA_CPTM (ID_LINHA, DS_LINHA) VALUES (6, 'LINHA_12');
INSERT INTO TB_LINHA_CPTM (ID_LINHA, DS_LINHA) VALUES (7, 'LINHA_13');

-- TB_DEPTO_MEIO_AMBIENTE
INSERT INTO TB_DEPTO_MEIO_AMBIENTE (ID_DEPTO, DS_DEPTO) VALUES (1, 'NORTE');
INSERT INTO TB_DEPTO_MEIO_AMBIENTE (ID_DEPTO, DS_DEPTO) VALUES (2, 'SUL');
INSERT INTO TB_DEPTO_MEIO_AMBIENTE (ID_DEPTO, DS_DEPTO) VALUES (3, 'LESTE');
INSERT INTO TB_DEPTO_MEIO_AMBIENTE (ID_DEPTO, DS_DEPTO) VALUES (4, 'OESTE');

-- COMMIT
COMMIT;
