using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CPTMBack.Migrations
{
    /// <inheritdoc />
    public partial class UseIdentityForLogIds : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Resync Oracle Identity sequences to avoid PK collision with existing rows.
            // The columns were created with START WITH 1 but rows were inserted with
            // explicit IDs. This resets each sequence to MAX(ID)+1.
            migrationBuilder.Sql(@"
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(ID_LOG), 0) + 1 INTO v_max FROM TB_LOG_ACAO;
    EXECUTE IMMEDIATE 'ALTER TABLE TB_LOG_ACAO MODIFY ID_LOG NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
    SELECT NVL(MAX(ID_LOG), 0) + 1 INTO v_max FROM TB_LOG_SINCRONIZACAO;
    EXECUTE IMMEDIATE 'ALTER TABLE TB_LOG_SINCRONIZACAO MODIFY ID_LOG NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH ' || v_max || ')';
END;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
