// <auto-generated />
using System;
using CPTMBack.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CPTMBack.Migrations
{
    [DbContext(typeof(ConnectContext))]
    partial class ConnectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CPTMBack.Domain.Model.TblDominio.TB_DEPTO_MEIO_AMBIENTEAggregate.TB_DEPTO_MEIO_AMBIENTE", b =>
                {
                    b.Property<int>("idDepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DEPTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDepto"));

                    b.Property<string>("dsDepto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_DEPTO");

                    b.HasKey("idDepto");

                    b.ToTable("TB_DEPTO_MEIO_AMBIENTE");

                    b.HasData(
                        new
                        {
                            idDepto = 1,
                            dsDepto = "NORTE"
                        },
                        new
                        {
                            idDepto = 2,
                            dsDepto = "SUL"
                        },
                        new
                        {
                            idDepto = 3,
                            dsDepto = "LESTE"
                        },
                        new
                        {
                            idDepto = 4,
                            dsDepto = "OESTE"
                        });
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblDominio.TB_LINHA_CPTMAggregate.TB_LINHA_CPTM", b =>
                {
                    b.Property<int>("idLinha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LINHA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLinha"));

                    b.Property<string>("dsLinha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_LINHA");

                    b.HasKey("idLinha");

                    b.ToTable("TB_LINHA_CPTM");

                    b.HasData(
                        new
                        {
                            idLinha = 1,
                            dsLinha = "LINHA_7"
                        },
                        new
                        {
                            idLinha = 2,
                            dsLinha = "LINHA_8"
                        },
                        new
                        {
                            idLinha = 3,
                            dsLinha = "LINHA_9"
                        },
                        new
                        {
                            idLinha = 4,
                            dsLinha = "LINHA_10"
                        },
                        new
                        {
                            idLinha = 5,
                            dsLinha = "LINHA_11"
                        },
                        new
                        {
                            idLinha = 6,
                            dsLinha = "LINHA_12"
                        },
                        new
                        {
                            idLinha = 7,
                            dsLinha = "LINHA_13"
                        });
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblDominio.TB_MUNICIPIOAggregate.TB_MUNICIPIO", b =>
                {
                    b.Property<int>("idMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MUNICIPIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMunicipio"));

                    b.Property<string>("dsMunicipio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_MUNICIPIO");

                    b.HasKey("idMunicipio");

                    b.ToTable("TB_MUNICIPIO");
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblDominio.TB_PERFIL_USUARIOAggregate.TB_PERFIL_USUARIO", b =>
                {
                    b.Property<int>("idPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PERFIL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPerfil"));

                    b.Property<string>("dsPerfil")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_PERFIL");

                    b.HasKey("idPerfil");

                    b.ToTable("TB_PERFIL_USUARIO");

                    b.HasData(
                        new
                        {
                            idPerfil = 1,
                            dsPerfil = "ADMINISTRADOR"
                        },
                        new
                        {
                            idPerfil = 2,
                            dsPerfil = "USUARIO_CAMPO"
                        });
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblDominio.TB_STATUS_DESVIO_AMBIENTALAggregate.TB_STATUS_DESVIO_AMBIENTAL", b =>
                {
                    b.Property<int>("idStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_STATUS");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idStatus"));

                    b.Property<string>("dsStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_STATUS");

                    b.HasKey("idStatus");

                    b.ToTable("TB_STATUS_DESVIO_AMBIENTAL");

                    b.HasData(
                        new
                        {
                            idStatus = 1,
                            dsStatus = "ABERTO"
                        },
                        new
                        {
                            idStatus = 2,
                            dsStatus = "EM_ANALISE"
                        },
                        new
                        {
                            idStatus = 3,
                            dsStatus = "RESOLVIDO"
                        },
                        new
                        {
                            idStatus = 4,
                            dsStatus = "CANCELADO"
                        });
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblDominio.TB_STATUS_REGISTROAggregate.TB_STATUS_REGISTRO", b =>
                {
                    b.Property<int>("idStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_STATUS");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idStatus"));

                    b.Property<string>("dsStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_STATUS");

                    b.HasKey("idStatus");

                    b.ToTable("TB_STATUS_REGISTRO");

                    b.HasData(
                        new
                        {
                            idStatus = 1,
                            dsStatus = "ATIVO"
                        },
                        new
                        {
                            idStatus = 2,
                            dsStatus = "INATIVO"
                        },
                        new
                        {
                            idStatus = 3,
                            dsStatus = "PENDENTE"
                        },
                        new
                        {
                            idStatus = 4,
                            dsStatus = "SINCRONIZADO"
                        });
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblDominio.TB_TIPO_EFLUENTEAggregate.TB_TIPO_EFLUENTE", b =>
                {
                    b.Property<int>("idTipoEfluente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO_EFLUENTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTipoEfluente"));

                    b.Property<string>("dsTipoEfluente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_TIPO_EFLUENTE");

                    b.HasKey("idTipoEfluente");

                    b.ToTable("TB_TIPO_EFLUENTE");

                    b.HasData(
                        new
                        {
                            idTipoEfluente = 1,
                            dsTipoEfluente = "ESGOTO"
                        },
                        new
                        {
                            idTipoEfluente = 2,
                            dsTipoEfluente = "OLEO"
                        },
                        new
                        {
                            idTipoEfluente = 3,
                            dsTipoEfluente = "QUIMICO"
                        },
                        new
                        {
                            idTipoEfluente = 4,
                            dsTipoEfluente = "INDUSTRIAL"
                        },
                        new
                        {
                            idTipoEfluente = 5,
                            dsTipoEfluente = "AGUA_CONTAMINADA"
                        });
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblDominio.TB_TRECHO_SENTIDOAggregate.TB_TRECHO_SENTIDO", b =>
                {
                    b.Property<int>("idTrecho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TRECHO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTrecho"));

                    b.Property<string>("dsTrecho")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_TRECHO");

                    b.HasKey("idTrecho");

                    b.ToTable("TB_TRECHO_SENTIDO");
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblDominio.TB_VIA_CPTMAggregate.TB_VIA_CPTM", b =>
                {
                    b.Property<int>("idVia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVia"));

                    b.Property<string>("dsVia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_VIA");

                    b.HasKey("idVia");

                    b.ToTable("TB_VIA_CPTM");

                    b.HasData(
                        new
                        {
                            idVia = 1,
                            dsVia = "VIA_1"
                        },
                        new
                        {
                            idVia = 2,
                            dsVia = "VIA_2"
                        });
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblPrincipais.PT_EFLUENTEAggregate.PT_EFLUENTE", b =>
                {
                    b.Property<string>("pkCdMeioAmbienteCptm")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("PK_CD_MEIO_AMBIENTE_CPTM");

                    b.Property<DateTime?>("dtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime?>("dtRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_REGISTRO");

                    b.Property<int>("idDeptoCampoAmbiente")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DEPTO_MEIO_AMBIENTE");

                    b.Property<int>("idLinha")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LINHA");

                    b.Property<int>("idMunicipio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MUNICIPIO");

                    b.Property<int>("idStatusDesvio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_STATUS_DESVIO");

                    b.Property<int>("idStatusRegistro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_STATUS_REGISTRO");

                    b.Property<int>("idTipoEfluente")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO_EFLUENTE");

                    b.Property<int>("idTrecho")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TRECHO");

                    b.Property<int>("idVia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VIA");

                    b.Property<decimal?>("txCoordenadaX")
                        .HasPrecision(18, 8)
                        .HasColumnType("DECIMAL(18,8)")
                        .HasColumnName("TX_COORDENADA_X");

                    b.Property<decimal?>("txCoordenadaY")
                        .HasPrecision(18, 8)
                        .HasColumnType("DECIMAL(18,8)")
                        .HasColumnName("TX_COORDENADA_Y");

                    b.Property<string>("txCorEfluente")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_COR_EFLUENTE");

                    b.Property<string>("txDestinacaoEfluente")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_DESTINACAO_EFLUENTE");

                    b.Property<string>("txEmailTecnicoResponsavel")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_EMAIL_TECNICO_RESPONSAVEL");

                    b.Property<string>("txEmpresaContratada")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_EMPRESA_CONTRATADA");

                    b.Property<string>("txEndereco")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_ENDERECO");

                    b.Property<string>("txKmPoste")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_KM_POSTE");

                    b.Property<string>("txLinkMapa")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_LINK_MAPA");

                    b.Property<string>("txNmElementoMonitoramento")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_NM_ELEMENTO_MONITORAMENTO");

                    b.Property<string>("txNomeFoto01")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_NOME_FOTO_01");

                    b.Property<string>("txNomeFoto02")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_NOME_FOTO_02");

                    b.Property<string>("txNomeFoto03")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_NOME_FOTO_03");

                    b.Property<string>("txNomeFoto04")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_NOME_FOTO_04");

                    b.Property<string>("txNomeTecnicoResponsavel")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_NOME_TECNICO_RESPONSAVEL");

                    b.Property<string>("txNrElementoMonitoramento")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_NR_ELEMENTO_MONITORAMENTO");

                    b.Property<string>("txNumeroContrato")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_NUMERO_CONTRATO");

                    b.Property<string>("txObservacao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_OBSERVACAO");

                    b.Property<string>("txOdorEfluente")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_ODOR_EFLUENTE");

                    b.Property<string>("txOrigemEfluente")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_ORIGEM_EFLUENTE");

                    b.Property<decimal?>("txPh")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("TX_PH");

                    b.Property<string>("txProcessoAmbiental")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_PROCESSO_AMBIENTAL");

                    b.Property<string>("txTelefoneTecnicoResponsavel")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_TELEFONE_TECNICO_RESPONSAVEL");

                    b.Property<decimal?>("txTemperatura")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("TX_TEMPERATURA");

                    b.Property<string>("txUnidadeVolume")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TX_UNIDADE_VOLUME");

                    b.Property<decimal?>("txVolumeEfluente")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("TX_VOLUME_EFLUENTE");

                    b.HasKey("pkCdMeioAmbienteCptm");

                    b.ToTable("PT_EFLUENTE");
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblPrincipais.RT_EFLUENTEAggregate.RT_EFLUENTE", b =>
                {
                    b.Property<int>("attachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ATTACHMENTID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("attachmentId"));

                    b.Property<string>("attName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ATT_NAME");

                    b.Property<string>("contentType")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONTENT_TYPE");

                    b.Property<byte[]>("data")
                        .HasColumnType("RAW(2000)")
                        .HasColumnName("DATA");

                    b.Property<int?>("dataSize")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DATA_SIZE");

                    b.Property<string>("relObjectId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REL_OBJECTID");

                    b.HasKey("attachmentId");

                    b.ToTable("RT_EFLUENTE");
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblSistema.TB_LOG_ACAOAggregate.TB_LOG_ACAO", b =>
                {
                    b.Property<int>("idLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLog"));

                    b.Property<string>("dsAcao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_ACAO");

                    b.Property<string>("dsIp")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_IP");

                    b.Property<DateTime>("dtAcao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ACAO");

                    b.Property<string>("idRegistro")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ID_REGISTRO");

                    b.Property<int>("idUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("nmTabela")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_TABELA");

                    b.HasKey("idLog");

                    b.ToTable("TB_LOG_ACAO");
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblSistema.TB_LOG_SINCRONIZACAOAggregate.TB_LOG_SINCRONIZACAO", b =>
                {
                    b.Property<int>("idLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLog"));

                    b.Property<string>("dsMensagem")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("dsStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_STATUS");

                    b.Property<DateTime>("dtSincronizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_SINCRONIZACAO");

                    b.Property<int>("idUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("idLog");

                    b.ToTable("TB_LOG_SINCRONIZACAO");
                });

            modelBuilder.Entity("CPTMBack.Domain.Model.TblSistema.TB_USUARIOAggregate.TB_USUARIO", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("dsEmail")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("dsLogin")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_LOGIN");

                    b.Property<string>("dsSenhaHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_SENHA_HASH");

                    b.Property<DateTime>("dtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<DateTime>("dtCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<bool>("flAtivo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<int>("idPerfil")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PERFIL");

                    b.Property<string>("nmUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_USUARIO");

                    b.HasKey("idUsuario");

                    b.ToTable("TB_USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
